### PR TITLE
fix for #195

### PR DESCRIPTION
**Pull request by thehesiod**
## What do these changes do?

Ensures we don't return bad connections back to the pool

## Are there changes in behavior for the user?

Bad connections will no longer poison the pool

## Related issue number

#195 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by thehesiod** [comment]
FYI: per https://www.python.org/dev/peps/pep-0249/#databaseerror, `OperationalError` means: `https://www.python.org/dev/peps/pep-0249/#databaseerror` so I think we're OK always closing the conn on one of these

**Comment by thehesiod** [comment]
btw let me know if you have an idea on how to test this

**Comment by thehesiod** [comment]
this is so frustrating trying to get these tests to pass, there's no reason why it keeps on failing to connect to the DB, argh

**Comment by thehesiod** [comment]
so summary: 
- running on jessie yields threads not existing: `Error in my_thread_global_end(): 54 threads didn't exit`.  If I enable my test then a bunch more tests start failing saying that an exception was never raised.
- running on stretch causes python to sporadically crash

between a rock and a hard place.

**Comment by thehesiod** [comment]
ok getting closer, now some kind of docker container reaping issue

**Comment by thehesiod** [comment]
done!

**Comment by jettify** [comment]
New release available on PyPI https://pypi.org/project/aioodbc/0.3.3/

**Pull request merged**
